Divmart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('webapp.urls')),
    path('useraccount/',include('useraccount.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('api/v1/',include('apis.urls')),
    path('member/',include('membership.urls')),
]

if settings.DEBUG:
    # urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apis/urls.py
from os import name
from django.contrib import admin
from django.urls import path,include
from apis.views import *
from rest_framework.authtoken import views

urlpatterns = (

    path('api-token-auth/', views.obtain_auth_token),
    # path('adminusers/',AdminListCreateView.as_view(), name='adminusers'),
    # path('adminusers/<int:id>',AdminDetailUpdateDelView.as_view(),name='admindetails'),
    path('staffusers/', StaffListCreateView.as_view(),name='staffusers'),
    # path('staffusers/<int:id>', StaffDetailUpdateDelView.as_view(),name='staffdetails'),
    path('banks',BankCreation.as_view(),name='bankccreation'),
    path('banks/<int:id>', BankDetailUpdateDelView.as_view(),name='bankdetails'),
    path('products/',ProductListCreateView.as_view(),name='productdetails'),
    path('products/<int:id>',ProductDetailUpdateDelView.as_view(),name='productdetails'),
    path('categories/',CategoryListCreateView.as_view(),name='vcategories'),
    path('categories/<int:id>',CategoryDetailUpdateDelView.as_view(),name='categorydetails'),
    path('brands/',BrandListCreateView.as_view(),name='brands'),
    path('brands/<int:id>',BrandDetailUpdateDelView.as_view(),name='branddetails'),
    path('units/',UnitsListCreateView.as_view(),name='units'),
    path('units/<int:id>',UnitsDetailUpdateDelView.as_view(),name='unitsdetails'),
    path('subcategories/',SubcatListCreateView.as_view(),name='subcategories'),
    path('suppliers/',SupplierListCreateView.as_view(),name='suppliers'),
    path('suppliers/<int:id>',SupplierDetailUpdateDelView.as_view(),name='supplierdetails'),
    path('customergroups/',CustomerGroupListCreateView.as_view(),name='customergroups'),
    path('customers/',CustomerListCreateView.as_view(),name='customers'),
    path('customers/<int:id>',CustomerDetailUpdateDelView.as_view(),name='cusomerdetails'),
    path('purchases/',PurchaseListCreateView.as_view(),name='purchases'),
    path('purchases/<int:id>',PurchaseDetailUpdateDelView.as_view(),name='purchasedetails'),
    # path('purchases/<product_name>',PurchaseReturnUpdateDelView.as_view(),name='purchasreturnedetails'),
    path('sells/<int:id>',SellDetailUpdateDelView.as_view(),name='sellldetails'),
    path('expenses/',AddExpensesView.as_view(),name='expenses'),
    path('expcategories/',AddExpensesCategoryView.as_view(),name='expcategories'),
    path('expcategories/<int:id>',AddExpensesDetailUpdateDelView.as_view(),name='expcategories'),
    path('purchaseinfo/<int:id>',PurchaseInfosDetailUpdateDelView.as_view(),name='purchaseinfo'),
    path('payments/<int:id>',PayementView.as_view(),name='payments'),


    # from my side..

    path('sells/',SellListCreateView.as_view(),name='sells'),
    path('barcode_api', ProductBarCode.as_view(), name='barcodes'),
    path('barcode_api/<barcode_no>', ProductsByBarcode.as_view(), name='barcode'),

)

dashboard/models.py
from django.contrib.auth.models import User
from useraccount.models import *
from div_settings.models import BusinessLocation, TaxRate


class Bank(models.Model):

    user = models.OneToOneField(User,on_delete=models.SET_NULL, null="true")
    account_holder_name = models.CharField(max_length=30)
    account_number = models.CharField(max_length=50)
    bank_name= models.CharField(max_length=50)
    branch = models.CharField(max_length=50)
    tax_payer_id = models.CharField(max_length=50)
    branch = models.CharField(max_length=50)
    bank_identifier_code = models.CharField(max_length=50)

    class Meta:
        db_table = 'Bank'


class SubCategory(models.Model):
    name = models.CharField(max_length=50)
    status = models.BooleanField(default=True)

    
    def __str__(self):
        return str(self.name)


class Category(models.Model):

    name = models.CharField(max_length=50)
    category_code = models.CharField(max_length=15)
    sub_category = models.ManyToManyField(SubCategory)
    discription = models.TextField(null=True,blank=True)
    status = models.BooleanField(default=True)
    
    def __str__(self):
        return str(self.name)


class Brand(models.Model):

    deltypes = (
        (0, False),
        (1, True),
    )
    brand_name = models.CharField(max_length=50)
    discription = models.CharField(max_length=50, null=True,blank=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return str(self.brand_name)


class Units(models.Model):

    dec = [('Y','Yes'),('N','No')]
    deltypes = (
        (0, False),
        (1, True),
    )
    name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=25)
    allow_decimal = models.CharField(max_length=1,choices=dec)
    status = models.BooleanField(default=True)

    def __str__(self):
        return str(self.name)


class PaymentAccount(models.Model):

    name = models.CharField(max_length=120)
    account_number = models.IntegerField()
    openning_balance = models.FloatField(null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    status = models.BooleanField(default=True)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)


class Product(models.Model):

    tax_choices = [('exclusive','exclusive'),('inclusive','inclusive')]
    prod_type = [('single','single'),('variable','variable')]

    product_name = models.CharField(max_length=50)
    business_location = models.ForeignKey(BusinessLocation, on_delete=models.SET_NULL, null=True)

    brand = models.ForeignKey(Brand,on_delete=models.SET_NULL, null=True, blank=True)
    unit = models.ForeignKey(Units,on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True, related_name='pro_category', blank=True)
    sub_category = models.ForeignKey(SubCategory,on_delete=models.SET_NULL, null=True, blank=True)
    SKU = models.CharField(max_length=50)
    barcode_type = models.CharField(max_length=50, null=True, blank=True)
    alert_quantity = models.CharField(max_length=30,null=True, blank=True)
    Product_description = models.CharField(max_length=500, null=True, blank=True)
    product_image = models.ImageField(upload_to='media/image/products',null=True, blank=True)
    weight = models.FloatField(default=0, null=True, blank=True)
    applicable_tax = models.ForeignKey(TaxRate, on_delete=models.SET_NULL, null=True, blank=True)
    product_type = models.CharField(max_length=10, choices=prod_type, null=True, blank=True)
    prod_mrp = models.FloatField(max_length=120, null=True, blank=True)
    sale_mrp = models.FloatField(default=0)
    selling_price_tax_type = models.CharField(max_length=10, choices=tax_choices, null=True, blank=True)
    selling_price = models.FloatField(default=0, null=True, blank=True)
    selling_price_exc_tax =  models.FloatField(default=0, null=True)
    purchase_price = models.FloatField(default=0, null=True, blank=True)
    purchase_price_exc_tax =  models.FloatField(default=0, null=True, blank=True)
    purchase_price_inc_tax =  models.FloatField(default=0, null=True, blank=True)
    margin =  models.FloatField(default=0, null=True, blank=True)
    current_stock = models.FloatField(default=0, null=True, blank=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return str(self.product_name)


class Add_Payments(models.Model):

    pay_choice = ((0, "cash"), (1, "card"), (2, "cheque"), (3, "Bank transfer"), (4, "other"),)

    amount = models.FloatField()
    payment_method = models.IntegerField(default=1, choices=pay_choice)
    payment_account = models.ForeignKey(PaymentAccount, on_delete=models.SET_NULL, null=True)
    payment_notes = models.CharField(max_length=100, null=True, blank=True)
    payment_due = models.FloatField(null=True, blank=True)
    payment_status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    

class Purchase_info(models.Model):

    # deltypes = ((0, False),(1, True),)
    per_choice = ((0, False),(1, True),)

    supplier = models.ForeignKey(SupplierUser,on_delete=models.SET_NULL, null=True)
    ref_no = models.CharField(max_length=40)
    purchase_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    # purchase_status = models.CharField(max_length=50)
    business_location = models.ForeignKey(BusinessLocation, on_delete=models.SET_NULL, null=True)
    documents = models.FileField(upload_to="purchase/docs", blank=True,null=True)
    grand_total = models.FloatField(default=0,null=True)
    discount_type = models.CharField(max_length=15,blank=True)
    Discount_amount = models.FloatField(default=0)
    discount = models.CharField(max_length=100,blank=True)
    purchase_tax = models.CharField(max_length=100,blank=True)
    purchase_tax_amount = models.FloatField(default=0)
    shipping_details = models.CharField(max_length=100)
    additional_ship_charges = models.FloatField(default=0)
    purchase_total = models.FloatField(default=0)
    Additional_notes = models.TextField()
    payment_info = models.ForeignKey(Add_Payments,on_delete=models.SET_NULL, null=True)
    purchase_return = models.IntegerField(default=0,choices=per_choice)
    status = models.BooleanField(default=True)

    def __str__(self):
        return str(self.supplier.first_name)


class Purchase(models.Model):

    deltypes = ((0, False),(1, True),)
    per_choice = ((0, False),(1, True),)

    product_name= models.ForeignKey(Product,on_delete=models.SET_NULL, null=True)
    purchase_details = models.ForeignKey(Purchase_info,on_delete=models.SET_NULL, null=True)
    purchase_quantity = models.BigIntegerField(default=0)
    unit_cost_before_discount = models.FloatField(default=0)
    unit_cost_before_tax = models.FloatField(default=0)
    discount_percentage = models.FloatField(default=0)
    sub_total =  models.FloatField(default=0)
    product_tax = models.FloatField(default=0)
    net_costs = models.FloatField(default=0)
    line_total = models.FloatField(default=0,null=True)
    profit_margin = models.FloatField(default=0)
    unit_selling_price = models.FloatField(default=0)
    status = models.BooleanField(default=True)
    purchase_return = models.IntegerField(default=0,choices=per_choice)

    def __str__(self):
        return '{}-{}'.format(self.product_name, self.net_costs)


class Sell(models.Model):

    dis_choice = (("F","Fixed"),("P","Percentage"))
    st_choice = (("F","Final"),("D","Draft"),("Q","Quotation"), ("C", "Credit"))
    per_choice = ((0, False),(1, True),)

    ref_no = models.CharField(max_length=40)
    business_location = models.ForeignKey(BusinessLocation, on_delete=models.SET_NULL, null=True)
    customer = models.ForeignKey(CustomerUser, on_delete=models.SET_NULL, null=True)
    pay_term = models.CharField(max_length=80, null=True, blank=True)
    sale_date = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=st_choice, default="Final")
    total_amount = models.FloatField()
    discount_type = models.CharField(max_length=15, choices=dis_choice, null=True, blank=True)
    discount_amount = models.FloatField(default=0.0)
    shipping_details = models.CharField(max_length=100, null=True, blank=True)
    shipping_charges = models.FloatField(default=0.0)
    total_payable = models.FloatField()
    sell_notes = models.TextField(null=True, blank=True)
    payment_info = models.ForeignKey(Add_Payments, on_delete=models.SET_NULL, null=True)
    invoice_no = models.IntegerField()
    order_tax = models.FloatField(null=True, blank=True)
    sale_return = models.IntegerField(default=0, choices=per_choice)
    cashier = models.ForeignKey(StaffUser, on_delete=models.SET_NULL, null=True)
    is_deleted = models.BooleanField(default=False)
    
    def __str__(self):
        return '{}-{}'.format(self.ref_no, self.total_payable)


class Barcode_storage(models.Model):

    product_name = models.ForeignKey(Product,on_delete=models.DO_NOTHING)
    barcode_type = models.CharField(max_length=50)
    barcode_no = models.CharField(max_length=200)

    def __str__(self):
        return str(self.product_name)


class Expenses_category(models.Model):

    name = models.CharField(max_length=50)
    category_code = models.CharField(max_length=50)
    status = models.BooleanField(default=True)

    def __str__(self):
        return str(self.name)


class Expenses(models.Model):

    status_choice = (('Paid' ,'Paid'), ('Unpaid', 'Unpaid'), ('Rejected', 'Rejected'))

    ref_no = models.CharField(max_length=50, blank=True)
    expense_category = models.ForeignKey(Expenses_category,on_delete=models.CASCADE)
    business_location = models.ForeignKey(BusinessLocation, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField()
    payment_status = models.CharField(max_length=50, choices=status_choice, default='Unpaid')

templates/divmart_dashboard/add_opening_stock.html
{% extends 'divmart_dashboard/index.html' %}
<<<<<<< HEAD
{% load static %} {% block home%}
<div class="container-fluid">
    <a class="btn btn-primary text-white"><i class="fa fa-arrow-left text-white" aria-hidden="true"></i>&nbsp;Back</a>
    <div class="card p-5 mt-3">
        
        <div class="row ">
            <p class="text-white bg-success col-lg-12 col-md-12 p-2">Add Opening Stock</p>
        </div>
        <div class="row">
            <table class="table  table-bordered table-sm">
                <thead class="dark">
                  <tr class="text-center">
                    <th scope="col">Product Name</th>
                    <th scope="col">Quantity Remaining</th>
                    <th scope="col">Unit Cost (Before Tax)</th>
                    <th scope="col">Subtotal (Before Tax)</th>
                    <th scope="col">Business Location</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <tr class="text-center">
                
                    <td><input type="text" class="form-control" name="product_name" readonly></td>
                    <td><input type="text" class="form-control" name="quantity_remaining" required></td>
                    <td><input type="text" class="form-control" name="unit_cost" required></td>
                    <td><input type="text" class="form-control" name="sub_total" required></td>
                    <td>
                        <select class="form-control" required>
                            <option value="">Please Select</option>
                            <option>xxxx</option>
                        </select>
                    </td>
                    <td><button type="button" class="btn btn-primary btn-sm"><i class="fa fa-plus text-white" aria-hidden="true"></i></button></td>
                  </tr>
               
                </tbody>
              </table>
</div>
            <div class="col-lg-12 col-md-12 float-right">
                <a class="btn btn-success text-white">SAVE</a>
            </div>
    </div>
</div>

=======
{% load static %}
{% block home%}
<div class="container-fluid">
	<a class="btn btn-primary text-white mb-3"><i class="fa fa-arrow-left text-white"
			aria-hidden="true"></i>&nbsp;Back</a>
	<div class="section card p-3" id="accordionExample" style="border-top:3px solid green">
		<div class="card-header bg-white" id="headingOne">
			<i class="fas fa- accordion text-primary" id="accordionExample" data-toggle="collapse"
				data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
				<h4 class="text-primary font-weight-bold">Add/Edit Opening Stock</h5>
			</i>
		</div>
		<form action="" method="post">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-6 col-lg-6">
					<label for="">Product Name</label>
					<input type="text" class="form-control prod_name" value="{% if product.product_name %}{{product.product_name}}{% endif %}" name="product_name" readonly>
				</div>
				<div class="col-md-6 col-lg-6">
					<label for="">Quantity</label>
					<input type="text" class="form-control" name="current_stock"value="{% if product.current_stock %}{{product.current_stock}}{% else %}0{% endif %}" onkeyup="multifunc()" required id="cur_stock">
				</div>
				<div class="col-md-6 col-lg-6 mt-2">
					<label for="">Unit Cost(Before Tax)</label>
					<input type="text" class="form-control" name="purchase_price_exc_tax" value="{% if product.purchase_price_exc_tax %}{{product.purchase_price_exc_tax}} {% elif product.prod_mrp %}{{product.prod_mrp}}{% else %}0{% endif %}" id="pur_b_tax">
				</div>
				<div class="col-md-6 col-lg-6 mt-2">
					<label for="">Sub Total</label>
					<input type="text" class="form-control" name="sub_total" id="sub_total" value="">
				</div>
				<div class="col-lg-6 col-md-6 mt-2">
					<label for="">Business Location</label>
					<select class="form-control" name="business_location" required>
						<option value="">Please Select</option>
						{% for location in locations %}
							<option value="{{location.id}}" 
								{% if location.id == product.business_location.id %}selected{% endif %}>{{location.name}}
							</option>
						{% endfor %}
					</select>
				</div>
			</div>
			<input type="submit" value="Submit" class="btn btn-primary w-25 float-right mt-2">
		</form>
	</div>
</div>
<script>
	function multifunc(){
		var quanti = document.getElementById('cur_stock');
		var ucbt = document.getElementById('pur_b_tax');
		var sub_total = document.getElementById('sub_total');
		
		if(quanti.value > 0){
			sub_total_val = quanti.value * ucbt.value;
			sub_total.value = parseFloat(sub_total_val).toFixed(2);
		}
		else{
			sub_total.value = 0.00;
		}
	}
</script>
>>>>>>> a23fd385bf445ef3171a544621b46d67ab51a2b5
{% endblock %}

templates/divmart_dashboard/credit_sell_report.html
{% extends 'divmart_dashboard/index.html' %} {% load i18n %} {% load static %} {% block home%}

<div class="container-fluid ">
	<h5>Credit Sale Report</h5>
	<div class="section card p-3" style="border-top: 3px solid green;">
		<div class="row">
			<div class="col-lg-12 box-solid">
				<a data-toggle="collapse" href="#collapsebox" role="button" aria-expanded="true"
					aria-controls="collapsebox">
					<div><i class="fa fa-filter"></i>Filters</div>
				</a>
				<div class="collapse show" id="collapsebox">
					<form action="" method="POST">
						{% csrf_token %}
						<div class="row">
							<div class="col-lg-4 filterbox">
								<label>Customer:</label>
								<!-- search here -->
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
									</div>
									<select class="form-control" name="customer">
										<option value="none">Please Select</option>
										{% for customer in customers %}
											<option value="{{customer.first_name}}">{{customer.first_name}}</option>
										{% endfor %}
									</select>
								</div>
							</div>
							<div class="col-lg-4 filterbox">
								<label>Business Location:</label>
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1"><i class="fa fa-map-marker"></i></span>
									</div>
									<select class="form-control" name="location">
										<option value="none">Please Select</option>
										{% for location in locations %}
											<option value="{{location.name}}">{{location.name}}</option>
										{% endfor %}
									</select>
								</div>
							</div>
							<!-- <div class="col-lg-4 pt-4 filterbox"> -->
								<!-- </div> -->
							</div>
							<input type="submit" class="btn btn-primary btn-block w-25 float-right" value="FILTER">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="section card p-3 oveflow-auto" style="border-top: 3px solid green;">
	<div class="section">
                <span class="float-right">
                      <a class="btn btn-secondary btn-sm mb-2" href=""> <i class="fa fa-print" aria-hidden="true"></i>&nbsp;
                        CSV </a>
                        <a class="btn btn-secondary btn-sm mb-2" href=""> <i class="fa fa-print" aria-hidden="true"></i>&nbsp;
                        EXCEL </a>
                        <a class="btn btn-secondary btn-sm mb-2" href=""> <i class="fa fa-print" aria-hidden="true"></i>&nbsp;
                        PDF </a>
                </span>
    </div>
		<table class="table table-sm" id="sell_pay_report">
			<thead>
				<tr>
					<th>Reference No</th>
					<th>Paid on</th>
					<th>Amount</th>
					<th>Customer</th>
					<th>Payment Method</th>
					<!-- <th>Sell</th>
					<th>Action</th> -->
				</tr>
			</thead>
			<tbody>
				{% for sale in credit_sale_list %}
				<tr>
					<td>{{sale.ref_no}}</td>
					<td>{{sale.sale_date}}</td>
					<td>₹ {{sale.payment_info.amount}}</td>
					<td>{{sale.customer.first_name}}</td>
					<td>{{sale.payment_info.get_payment_method_display}}</td>
					<!-- <td></td>
					<td><input type="button" value="View" class="btn btn-primary btn-sm"></td> -->
				</tr>
				{% endfor %}
			</tbody>
			<!-- footer row -->
			<!-- <tr>
				<th colspan="2" class="text-center">Total</td>
				<th class="text-center">₹ 0.00</th>
				<th colspan="4" class="text-center"></th>
			</tr> -->
	
		</table>
	</div>
</div>
<script>
    $(document).ready(function () {
        $('#sell_pay_report').dataTable();
    });
</script>
{%endblock%}

templates/divmart_dashboard/edit_unit.html
{% extends 'divmart_dashboard/index.html' %} {% load i18n %} {% load static %} {% block home%}

<div class="container">
    <h4>Update units - <span class="text-danger">{{unit_obj.name}}</span></h4>
    <div class="section card p-5" style="border-top: 3px solid green;">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label>Name:*</label>
                <input type="text" class="form-control" name="name" placeholder="name" value="{{unit_obj.name}}">
            </div>
            <div class="form-group row">
                <label>Short Name:*</label>
                <input type="text" class="form-control" name="short_name" placeholder="short name"
                    value="{{unit_obj.short_name}}">
            </div>
            <div class="form-group row">
                <label>Allow Decimal:*</label>
                <select class="form-control" name="allow_decimal">
                    <option value="Y" {% if unit_obj.allow_decimal == 'Y' %} selected {% endif %}>Yes</option>
                    <option value="N" {% if unit_obj.allow_decimal == 'N' %} selected {% endif %}>No</option>
                </select>
            </div>
            <!-- <div class="form-group row"> -->
            <!-- <div class="col-lg-12 col-md-12">
                    <input type="checkbox" /><label class="ml-2">Add as multiple of other unit</label>
                </div> -->
            <!-- </div> -->
            <input type="submit" class="btn btn-primary w-100 mb-4 mt-3" value="Save">
        </form>
    </div>
</div>

{%endblock%} {% block alljs %}


{%endblock%}

templates/divmart_dashboard/sell_payment_report.html
{% extends 'divmart_dashboard/index.html' %} {% load i18n %} {% load static %} {% block home%}

<div class="container-fluid ">
	<h5>Sell Payment Report</h5>
	<div class="section card p-3" style="border-top: 3px solid green;">
		<div class="row">
			<div class="col-lg-12 box-solid">
				<a data-toggle="collapse" href="#collapsebox" role="button" aria-expanded="true"
					aria-controls="collapsebox">
					<div><i class="fa fa-filter"></i>Filters</div>
				</a>
				<div class="collapse show" id="collapsebox">
					<form action="" method="POST">
						{% csrf_token %}
						<div class="row">
							<div class="col-lg-4 filterbox">
								<label>Customer:</label>
								<!-- search here -->
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
									</div>
									<select class="form-control" name="customer">
										<option value="">Please Select</option>
										{% for customer in customers %}
											<option value="{{customer.first_name}}">{{customer.first_name}}</option>
										{% endfor %}
									</select>
								</div>
							</div>
							<div class="col-lg-4 filterbox">
								<label>Business Location:</label>
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1"><i class="fa fa-map-marker"></i></span>
									</div>
									<select class="form-control" name="location">
										<option value="">Please Select</option>
										{% for location in locations %}
											<option value="{{location.name}}">{{location.name}}</option>
										{% endfor %}
									</select>
								</div>
							</div>
							<!-- <div class="col-lg-4 pt-4 filterbox"> -->
								<!-- </div> -->
							</div>
							<input type="submit" class="btn btn-primary btn-block w-25 float-right" value="FILTER">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="section card p-3 oveflow-auto" style="border-top: 3px solid green;">
	<div class="section">
                <span class="float-right">
                      <a class="btn btn-secondary btn-sm mb-2" href=""> <i class="fa fa-print" aria-hidden="true"></i>&nbsp;
                        CSV </a>
                        <a class="btn btn-secondary btn-sm mb-2" href=""> <i class="fa fa-print" aria-hidden="true"></i>&nbsp;
                        EXCEL </a>
                        <a class="btn btn-secondary btn-sm mb-2" href=""> <i class="fa fa-print" aria-hidden="true"></i>&nbsp;
                        PDF </a>
                </span>
    </div>
		<table class="table table-sm" id="sell_pay_report">
			<thead>
				<tr>
					<th>Reference No</th>
					<th>Paid on</th>
					<th>Amount</th>
					<th>Customer</th>
					<th>Payment Method</th>
					<!-- <th>Sell</th>
					<th>Action</th> -->
				</tr>
			</thead>
			<tbody>
				{% for sale in sales %}
				<tr>
					<td>{{sale.ref_no}}</td>
					<td>{{sale.sale_date}}</td>
					<td>₹ {{sale.payment_info.amount}}</td>
					<td>{{sale.customer.first_name}}</td>
					<td>{{sale.payment_info.get_payment_method_display}}</td>
					<!-- <td></td>
					<td><input type="button" value="View" class="btn btn-primary btn-sm"></td> -->
				</tr>
				{% endfor %}
			</tbody>
			<!-- footer row -->
			<!-- <tr>
				<th colspan="2" class="text-center">Total</td>
				<th class="text-center">₹ 0.00</th>
				<th colspan="4" class="text-center"></th>
			</tr> -->
	
		</table>
	</div>
</div>
<script>
    $(document).ready(function () {
        $('#sell_pay_report').dataTable();
    });
</script>
{%endblock%}